### ISSUE TITLE
Docs not parsing correctly?

### ISSUE THREAD

**Issue by pherris** [awsdocs/aws-java-developer-guide#19]
It seems like something is going on with the parsing of [this document](https://github.com/awsdocs/aws-java-developer-guide/blob/master/doc_source/swf-hello.rst) into [this page](http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/swf-hello.html).

The last lines of these generated code snippets are missing:

<img width="866" alt="screen shot 2017-02-24 at 11 45 37 am" src="https://cloud.githubusercontent.com/assets/2084598/23314266/d3dddd84-fa86-11e6-8109-ee5ebb83f809.png">

Thanks!

**Comment by EronHennessey** [comment]
Hi @pherris, thanks for pointing this out.

I've updated the topic so it pulls the correct lines from the source files and republished the guide:

* http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/swf-hello.html
