### ISSUE TITLE
Tagging instances code incorrect

### ISSUE THREAD

**Issue by golharam** [awsdocs/aws-java-developer-guide#2]
The code shown under "How to Tag Your Spot Requests and Instances" is incorrect.  It currently shows how to Cancel or Terminate instances, not tag them.

This is in https://github.com/awsdocs/aws-java-developer-guide/blob/master/doc_source/tutorial-spot-adv-java.rst

**Comment by EronHennessey** [comment]
Thanks @golharam, you're certainly correct, there's nothing there that shows tagging. I'll work on a fix for that section.

**Comment by EronHennessey** [comment]
Sorry for the delay, I finally got a chance to address this issue and update the topic, which now covers tagging spot requests and instances:
- [How to tag your spot requests and instances](http://docs.aws.amazon.com/AWSSdkDocsJava/latest/DeveloperGuide/tutorial-spot-adv-java.html#tutor-spot-adv-tags)

The cancel/terminate requests and instances example has been moved into a more properly-named section:
- [Canceling spot requests and terminating instances](http://docs.aws.amazon.com/AWSSdkDocsJava/latest/DeveloperGuide/tutorial-spot-adv-java.html#canceling-spot-requests-and-terminating-instances)
