### ISSUE TITLE
TransferManager progress listener example uses deprecated methods

### ISSUE THREAD

**Issue by millems** [awsdocs/aws-java-developer-guide#24]
From Gitter: http://docs.aws.amazon.com/AmazonS3/latest/dev/HLTrackProgressMPUJava.html uses `PutObjectRequest.setProgressListener`, which is deprecated. The correct method is `setGeneralProgressListener` (or `withGeneralProgressListener`), and a different `ProgressListener` and ` ProgressEvent` implementation should be used that is not S3-specific.

**Comment by millems** [comment]
Also here: http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/examples-s3-transfermanager.html

**Comment by jschwarzwalder** [comment]
I think this has been fixed. 

Please reopen if this is still and issue.
