### ISSUE TITLE
SDK samples refer to master instead of 1.11.22

### ISSUE THREAD

**Issue by vamsiampolu** [awsdocs/aws-java-developer-guide#25]
The sdk samples take you to master which has the Builder API which was not available to me, the documentation needs to point to the rightv version of the documentation which one can use with scala. 

This did not work: https://github.com/aws/aws-sdk-java/tree/master/src/samples

This worked: https://github.com/aws/aws-sdk-java/tree/1.11.22/src/samples

Also, the scala example is out of date. Please update the docs as they are very misleading and not beginner friendly https://aws.amazon.com/blogs/compute/writing-aws-lambda-functions-in-scala/

**Comment by jschwarzwalder** [comment]
We've changed how we do examples now. 

If this is still a problem, please reopen a ticket.
