### ISSUE TITLE
Best practices for DynamoDB

### ISSUE THREAD

**Issue by nitrocode** [awsdocs/aws-java-developer-guide#28]
After reading about the [DynamoDBMapper](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.html), I figured my DynamoDB implementation was lacking. 

I'm really interested to see best practices of implementing a DynamoDB class with Put and Get item functions. Is the DynamoDBMapper the best way to do it or is it better to implement without all the annotations? What are the advantages / disadvantages?

Thank you!

**Comment by ghost** [comment]
Thanks for the suggestion. I've added it to the team's list for future consideration.
