### ISSUE TITLE
Broken Link on the SWF Developer Guide

### ISSUE THREAD

**Issue by andersonkyle** [awsdocs/aws-java-developer-guide#3]
The [SWF Developer Guide](http://docs.aws.amazon.com/amazonswf/latest/developerguide/swf-welcome.html) contains a broken link to the Java specific SWF developer guide.

It can be found under the SDK's section:
- [AWS Java Developer Guide | Amazon SWF](http://docs.aws.amazon.com/AWSSdkDocsJava/latest/DeveloperGuide/prog-services-swf.html)

**Comment by EronHennessey** [comment]
Greetings @kanderson450,

That link works for me, if you're referring to this one:

* http://docs.aws.amazon.com/amazonswf/latest/awsflowguide/

Which is found on [this page](http://alpha-docs-aws.amazon.com/AWSSdkDocsJava/latest/DeveloperGuide/prog-services-swf.html).

Does that link work for you?

**Comment by EronHennessey** [comment]
Ah, I see the issue!  Thanks.  Although the SWF dev guide / Java Flow guide aren't open-sourced, I'll field it. ;)

**Comment by andersonkyle** [comment]
Yeah, I figured this repo was close enough.  Thanks.

**Comment by EronHennessey** [comment]
The link is fixed (I've updated the original comment with the correct link, as well). Thanks again!
