### ISSUE TITLE
Inconsistent package naming in SWF hello-world tutorial

### ISSUE THREAD

**Issue by edenhochbaum** [awsdocs/aws-java-developer-guide#30]
[the tutorial](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/swf-hello.html#swf-hello-run-register) uses package `aws.example.helloswf`, but later, the templating system resolves this as `example.swf.hello`.

the [example code directory](https://github.com/awsdocs/aws-doc-sdk-examples/blob/master/java/example_code/swf/src/main/java/aws/example/helloswf/HelloTypes.java) is just structured differently than the user's directory because of the way the mvn project is initialized.

**Comment by edenhochbaum** [comment]
Why closed?

**Comment by jschwarzwalder** [comment]
I recently updated the SWF example and used code snippets to reference the code examples so that it isn't shifted anymore.

**Comment by edenhochbaum** [comment]
Thanks.  Seems good to include that kind of info on the closed issue.
