### ISSUE TITLE
Imports of source code are linking to moving targets

### ISSUE THREAD

**Issue by edenhochbaum** [awsdocs/aws-java-developer-guide#38]
Similar to #19 - throughout the [hello-world docs](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/swf-hello.html), the imported source code is resolving to the wrong lines.  It looks like there are just hard-coded line numbers here (literal-includes); but the underlying source code is [changing](https://github.com/awsdocs/aws-doc-sdk-examples/commits/feb19121aafa9aeb3311afbd54d106943ab270ca/java/example_code/swf/src/main/java/aws/example/helloswf/WorkflowWorker.java) regularly.  **Linking to fixed line numbers in a remote living-document doesn't seem like a winning strategy.**

**Comment by jschwarzwalder** [comment]
Thank you for your comment. We are in the process of switching the line numbers to code snippets so there will be less shifting. 

I am going to close this ticket as it is something we are actively working to fix. 

Thank you for taking the time to send feedback.
