### ISSUE TITLE
Please do a Fargate Example

### ISSUE THREAD

**Issue by jolo-dev** [awsdocs/aws-java-developer-guide#46]
Hi,

I would be happy if there is an example with Fargate.
Preferable it should list all the S3-buckets from the container. 

I am currently struggling with the `AwsCredentialProvider`.

Thank you!

**Comment by ghost** [comment]
Thanks for the suggestion. I've moved it over to our code examples repo for tracking purposes. See https://github.com/awsdocs/aws-doc-sdk-examples/issues/844. 

Paul
AWS Documentation
