### ISSUE TITLE
Cannot import entire SDK

### ISSUE THREAD

**Issue by tdewitt-atl** [awsdocs/aws-java-developer-guide#5]
From this page: https://github.com/awsdocs/aws-java-developer-guide/blob/master/doc_source/setup-project-maven.rst

I have tried importing the entire SDK with

```
<dependencies>
    <dependency>
        <groupId>com.amazonaws</groupId>
        <artifactId>aws-java-sdk</artifactId>
    </dependency>
</dependencies>
```

But get an error that I must specify a version.

If I specify a version, this dependency works, but that defeats the purpose of the BOM.

Is it possible to import the whole SDK using the BOM?

For reference, BOM:

```
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-java-sdk-bom</artifactId>
      <version>1.11.22</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  </dependencies>
</dependencyManagement>
```

**Comment by EronHennessey** [comment]
Thanks for the issue!

In my own testing, I can verify that it's not currently working for me: specifying _aws-java-sdk_ as the dependency after using the bom results in the same error you saw. Specifying a particular service (_aws-java-sdk-s3_) works as expected.

I'll verify the behavior with the SDK team and update the docs as necessary.

**Comment by EronHennessey** [comment]
OK, the docs have been updated--the published version should be updated fairly soon.  Thanks again for the issue, keeping our docs honest. :)
