### ISSUE TITLE
CryptoRangeGetMode.ALL deprecated and alternate for it 

### ISSUE THREAD

**Issue by hacker7897iiita** [awsdocs/aws-java-developer-guide#56]
In the file [doc_source/s3-encryption-migration.md](https://github.com/awsdocs/aws-java-developer-guide/blob/399137c1587710962a0cb372f327cc076d319d98/doc_source/s3-encryption-migration.md) it suggests to use withRangeGetMode(CryptoRangeGetMode.ALL) for multipart downloads using Amazon S3 TransferManager. But CryptoRangeGetMode.ALL shows it is deprecated. What is the reason behind it and what is alternative to perform multipart downloads using Amazon S3 TransferManager?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
